name: Publish Website
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: windows-2008
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 3
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://47.95.206.69/docs/
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
